### ISSUE TITLE
Create Locals does does not create a local array for sqlexec

### ISSUE THREAD

**Issue by calloatti** [VFPX/Thor#123] opened 2023-06-18 00:00 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Type this in a prg: `sqlexec(handle, 'sqlcommand', 'cursorname', acountinfo) `
2. Click on the Create LOCALs toolbar button
3. No `local array acountinfo[1]` is created

Note: The option Arrays as LOCAL ARRAY is enabled in Create Locals config screen

### ✔️ Expected result

A `local array acountinfo[1]` line for the array acountinfo 

### ❌ Actual result

No  `local array acountinfo[1]` line

## 📷 Screenshots

N/A

**Comment by Jimrnelson** [comment] 2023-06-28 16:48
> There are several problems.
> 
> * the locals works on hungarian notation, like lcXXX for string or llXXX for boolean. This is, a local starts with **l**

This is not correct.  There is nothing in Create Locals that makes any assumption about the naming convention for variable names.

> * there is no handler to parse any function, just for some A*(, where the first parameter  is an array

That is also not correct.  There is at least one function where the created array is the second parameter (ACopy)

> So, at least you must name your var **lacountinfo**, or it will not work. Possibly it is used later with ( or [ and can be identified as array, even if sqlexec is not parsed for array.

This is also not correct.  You should be able to name your variable using any valid name.  A few lines of code would have to be added to handle SQLEXEC and that code would look remarkably like the code that handles ACopy.

**Comment by lscheffler** [comment] 2023-06-28 17:23
It was more a description of the state we have.

> > There are several problems.
> > 
> > * the locals works on hungarian notation, like lcXXX for string or llXXX for boolean. This is, a local starts with **l**
> 
> This is not correct. There is nothing in Create Locals that makes any assumption about the naming convention for variable names.   

Yes and No. None of us is right. There is a setting controlling the behaviour. Guess who's standard is *With Lowercase "L" only* :) \(－‸ლ)    
@calloatti , just check this setting in *Thor / Configure / Options / Create Locals*

> 
> > * there is no handler to parse any function, just for some A*(, where the first parameter  is an array
> 
> That is also not correct. There is at least one function where the created array is the second parameter (ACopy)

Come on, in general ...

> > So, at least you must name your var **lacountinfo**, or it will not work. Possibly it is used later with ( or [ and can be identified as array, even if sqlexec is not parsed for array.
> 
> This is also not correct. You should be able to name your variable using any valid name. A few lines of code would have to be added to handle SQLEXEC and that code would look remarkably like the code that handles ACopy.

1. see above
2. sure, one could do this. volunteers?

**Comment by Jimrnelson** [comment] 2023-06-28 18:37
I'd be happy to volunteer for this, as it's really a minor correction in method `CreateNewLocals`

However, I am not going to do so because of the difficulty in testing.  It's been a LOOOONG time since working on it and I know it would take longer for me to set up testing then it would to write the code.

I can, however, provide an untested version if there is interest.

On a slightly related issue, this is another instance of the problem of having so many tools that are embedded in PEM Editor without having any reason for them to be embedded (except for history).  Earlier this year I extracted Go To Definition, as I had some significant enhancements planned.  This little change, however, would not be worth that effort.

**Comment by lscheffler** [comment] 2023-06-28 18:57
I ended up compiling PEMEditor to the THOR folder (using command line like    
```
build app "E:\thor\thor\Thor\Tools\Apps\PEM Editor\PEMEditor.app" from "E:\PEMEditor\downloads\Source\pemeditor.pjx"
```    
and run the app from Thor, so it was relative simple to test. CFU will simple replace with the next update.    

If CREATE LOCALS is turned on in BeautifyX, I just use this, since I have a shortcut.   

Any code snippet with the function mentioned will do.

**Comment by Jimrnelson** [comment] 2023-06-29 17:10
@lscheffler 

Thanks, that made it easy, I have pushed a couple of commits to handle this and PEMEditor issue 47 (PEMEditor no longer registering itself properly with Thor.)

The SQLExec issue can be tested, but PEMEditor registering with Thor can only be tested by releasing to CFU and seeing if it works as intended.  I will do so as soon as it is released.  (I have no intention of doing so).

**Comment by Jimrnelson** [comment] 2023-06-29 17:25
Addenda --

My fix to determine the array created by calling SQLExec (fourth parameter) will fail if the second parameter, the SQL statement, is a character constant containing a comma.

**Comment by lscheffler** [comment] 2023-06-29 18:29
@Jimrnelson    
> The SQLExec issue can be tested, but PEMEditor registering with Thor can only be tested by releasing to CFU and seeing if it works as intended. I will do so as soon as it is released. (I have no intention of doing so).

I do not really understand this, but I do not intend to do something on PEMEditor soon.

----
To the comma problem. As I told, I'm not familiar with this function, SQL string I guess.

All I see is something with RAT or RegExp like `",\s*([a-zA-Z_]\w*)\s*\)$"` and read the group.
I bet somebody decided to skip the function for this reason ....

My 0.02  cent. What happens, if you use SQLEXEC with some array and use this array somewhere later in anything then a parameter to an UDF? A* function or like myArray(1) (Fitting the name to the locals "L" option, logically )   
Then it will be very rare, and the effort to fix the problem will be to high developing and runtime wise.

If you decide to skip it, put a comment about this, please.

**Comment by Jimrnelson** [comment] 2023-06-30 13:24
I had thought I had a workable solution for this problem but have abandoned it because my solution has unintended and undesirable consequences,

SQLEXEC uses up to four parameters:  `SQLEXEC(nStatementHandle [, cSQLCommand [, cCursorName[, aCountInfo]]])`

My solution, the same as used for other functions that create arrays, works fine as long as all of the parameters are simple variable names.  (It does so using STREXTRACT to get the list of parameters and GETWORDNUM to get the 4th parameter).

This solution fails miserably, though, if any of the parameters contain a comma or right parenthesis.

`SQLEXEC(nStatementHandle , "Select Field1, Field2 fromTable", cCursorName[, aCountInfo]]])`

Clearly this is a solvable problem, but it is not an easy one, as parsing a line of text (matching up parenthesis or the three different flavors of text delimiters) to determine that fourth parameter takes quite some work.

I don't think it's worth the effort for me to spend my time on it.

**Comment by Jimrnelson** [comment] 2023-06-30 14:00
@lscheffler 

> Possibly it is used later with ( or [ and can be identified as array, even if sqlexec is not parsed for array.

Create Locals does _not_ look at references to variables to try to infer if they used as arrays.  It only looks at where variables are assigned.

**Comment by lscheffler** [comment] 2023-07-03 09:22
All I know is, AddNewLocal is ckecking for \(\[. What exactly goes into this method is a different problem.  :)

**Comment by Jimrnelson** [comment] 2023-07-03 11:49
> Create Locals does not look at references to variables to try to infer if they used as arrays. It only looks at where variables are assigned.

Clarification:  The important word in my statement was "references".

1. When a variable is assigned and it looks like a array, it is created as one.    Thus  `laArray[1] = 0` creates a local array.
1. However, since 'Create Locals' only looks at assignments, any other reference to a variable that looks like an array does not.  Thus, `lcSomething = laArray[1]` does  nothing.

I don't think I like the first case (even though it's clearly my code and has been there forever.)  If the only way that a variable was known to be an array  is from that statement, how was it created?  It certainly could be a reference to a private or public variable (yeah, people do that) and then creating a local would be wrong.  It just seems wrong, or at least unnecessary.  

Not that I'm suggesting a change to it.

**Comment by lscheffler** [comment] 2023-07-03 14:40
ACK

**Comment by Jimrnelson** [comment] 2023-08-19 21:51
I am closing this one only because I cannot see anything more than can be done with it.

**Closed by Jimrnelson** 2023-08-19 21:51 UTC
