### ISSUE TITLE
Go Fish 5 bombs

### ISSUE THREAD

**Issue by KenAGreen** [VFPX/Thor#125] opened 2023-06-22 18:08 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Within VFP I type: DO THOR
2. I then try to run Go Fish 5
3. But I get an error

### ✔️ Expected result
Go Fish 5 up and running

### ❌ Actual result
Error message:
![GoFish](https://github.com/VFPX/Thor/assets/9791583/df15bdee-129e-4d10-8ffe-6c62313e329e)

Then, I try to run Go Fish 4 and it starts OK. Exiting VFP and getting back in with THOR, and only get the choice of resetting options. I click that and nothing happens - see 2nd screenshot:
![GoFishOptions](https://github.com/VFPX/Thor/assets/9791583/9d2f1447-5b60-4c68-817d-e0c75d6890ef)

**Comment by Jimrnelson** [comment] 2023-06-22 18:36
Actually, this looks like a bug in GF6, not GF5.

In any case, this bug is exactly the same bug I reported earlier today.  

I cured mine by deleting folder `Home(7) + 'GoFish_' and then reinstalling GF6

**Comment by KenAGreen** [comment] 2023-06-22 19:57
You're right: the version number is 6 but the app name still says 5. I looked for other users with the same problem but must have missed your entry.

After doing what you'd suggested, I retried it and still got a problem. But, I also got a notice from Scheffler, I presume the author, expressing frustration with the bug and asking for a zip file of the HOME(7) GoFish_Backup folder.

So, he's certainly trying to fix it.

Thanks for your help,
Ken Green

On 6/22/2023 11:36:18 AM, Jimrnelson ***@***.***> wrote:
Actually, this looks like a bug in GF6, not GF5.
In any case, this bug is exactly the same bug I reported earlier today.
I cured mine by deleting folder `Home(7) + 'GoFish_' and then reinstalling GF6

**Comment by Jimrnelson** [comment] 2024-01-02 23:04
@KenAGreen 

I am closing this issue as there has been no further comment since June and it was actually a GF issue in the first place.

**Closed by Jimrnelson** 2024-01-02 23:04 UTC

**Comment by KenAGreen** [comment] 2024-01-02 23:10
OK with me.

Thanks,
Ken

On 1/2/2024 3:04:20 PM, Jimrnelson ***@***.***> wrote:
@KenAGreen [https://github.com/KenAGreen]
I am closing this issue as there has been no further comment since June and it was actually a GF issue in the first place.

**Comment by lscheffler** [comment] 2024-01-03 10:52
@Jimrnelson, @KenAGreen The problem is bound to the update GF5 to GF6. So if it run once, it will never happen again. 

Somehow issues of GF notified here must be relayed to GF
